/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace DETHRoll {
  export type GameStruct = {
    player1: AddressLike;
    player2: AddressLike;
    startTimestamp: BigNumberish;
    betAmount: BigNumberish;
    lastRandomNumber: BigNumberish;
    lastPlayer1: boolean;
    rollsCount: BigNumberish;
    winner: AddressLike;
  };

  export type GameStructOutput = [
    player1: string,
    player2: string,
    startTimestamp: bigint,
    betAmount: bigint,
    lastRandomNumber: bigint,
    lastPlayer1: boolean,
    rollsCount: bigint,
    winner: string
  ] & {
    player1: string;
    player2: string;
    startTimestamp: bigint;
    betAmount: bigint;
    lastRandomNumber: bigint;
    lastPlayer1: boolean;
    rollsCount: bigint;
    winner: string;
  };

  export type PlayerStruct = { discord: string; mainWallet: AddressLike };

  export type PlayerStructOutput = [discord: string, mainWallet: string] & {
    discord: string;
    mainWallet: string;
  };
}

export interface DETHRollInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "_qrngUint256"
      | "airnode"
      | "depositErc20"
      | "endpointIdUint256"
      | "expectingRequestWithIdToBeFulfilled"
      | "getGame"
      | "getMinePendingGame"
      | "getPendingGameForWallet"
      | "getPlayer"
      | "getRandomNumber"
      | "getUserBalance"
      | "initGame"
      | "joinGame"
      | "owner"
      | "register"
      | "renounceOwnership"
      | "resetPlayer"
      | "roll"
      | "sponsorWallet"
      | "terminatePendingGame"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GameCreated"
      | "GameJoin"
      | "GameWon"
      | "OwnershipTransferred"
      | "Roll"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "_qrngUint256",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "airnode", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "depositErc20",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "endpointIdUint256",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "expectingRequestWithIdToBeFulfilled",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getGame", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getMinePendingGame",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingGameForWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRandomNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initGame",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinGame",
    values: [string, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [AddressLike, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resetPlayer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "roll",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sponsorWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "terminatePendingGame",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "_qrngUint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "airnode", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositErc20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "endpointIdUint256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "expectingRequestWithIdToBeFulfilled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMinePendingGame",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingGameForWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPlayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRandomNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "joinGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resetPlayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "roll", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sponsorWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "terminatePendingGame",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace GameCreatedEvent {
  export type InputTuple = [amount: BigNumberish, player1: AddressLike];
  export type OutputTuple = [amount: bigint, player1: string];
  export interface OutputObject {
    amount: bigint;
    player1: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameJoinEvent {
  export type InputTuple = [
    gameId: string,
    amount: BigNumberish,
    player2: AddressLike,
    player1: AddressLike
  ];
  export type OutputTuple = [
    gameId: string,
    amount: bigint,
    player2: string,
    player1: string
  ];
  export interface OutputObject {
    gameId: string;
    amount: bigint;
    player2: string;
    player1: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameWonEvent {
  export type InputTuple = [
    gameId: string,
    winner: AddressLike,
    loser: AddressLike,
    wonAmount: BigNumberish
  ];
  export type OutputTuple = [
    gameId: string,
    winner: string,
    loser: string,
    wonAmount: bigint
  ];
  export interface OutputObject {
    gameId: string;
    winner: string;
    loser: string;
    wonAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RollEvent {
  export type InputTuple = [
    gameId: string,
    player: AddressLike,
    rolledNumber: BigNumberish
  ];
  export type OutputTuple = [
    gameId: string,
    player: string,
    rolledNumber: bigint
  ];
  export interface OutputObject {
    gameId: string;
    player: string;
    rolledNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DETHRoll extends BaseContract {
  connect(runner?: ContractRunner | null): DETHRoll;
  waitForDeployment(): Promise<this>;

  interface: DETHRollInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  _qrngUint256: TypedContractMethod<[], [bigint], "view">;

  airnode: TypedContractMethod<[], [string], "view">;

  depositErc20: TypedContractMethod<
    [amount: BigNumberish, sigWallet: AddressLike],
    [void],
    "payable"
  >;

  endpointIdUint256: TypedContractMethod<[], [string], "view">;

  expectingRequestWithIdToBeFulfilled: TypedContractMethod<
    [arg0: BytesLike],
    [boolean],
    "view"
  >;

  getGame: TypedContractMethod<
    [gameId: string],
    [DETHRoll.GameStructOutput],
    "view"
  >;

  getMinePendingGame: TypedContractMethod<
    [player: AddressLike],
    [DETHRoll.GameStructOutput],
    "view"
  >;

  getPendingGameForWallet: TypedContractMethod<
    [player: AddressLike],
    [DETHRoll.GameStructOutput],
    "view"
  >;

  getPlayer: TypedContractMethod<
    [player: AddressLike],
    [DETHRoll.PlayerStructOutput],
    "view"
  >;

  getRandomNumber: TypedContractMethod<[], [bigint], "view">;

  getUserBalance: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  initGame: TypedContractMethod<
    [_betAmount: BigNumberish, player1: AddressLike],
    [void],
    "nonpayable"
  >;

  joinGame: TypedContractMethod<
    [gameId: string, oponent: AddressLike, player2: AddressLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  register: TypedContractMethod<
    [_mainWallet: AddressLike, _discord: string, _sigWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resetPlayer: TypedContractMethod<[player: AddressLike], [void], "nonpayable">;

  roll: TypedContractMethod<
    [gameId: string, player: AddressLike],
    [void],
    "nonpayable"
  >;

  sponsorWallet: TypedContractMethod<[], [string], "view">;

  terminatePendingGame: TypedContractMethod<
    [player: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "_qrngUint256"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "airnode"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "depositErc20"
  ): TypedContractMethod<
    [amount: BigNumberish, sigWallet: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "endpointIdUint256"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "expectingRequestWithIdToBeFulfilled"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getGame"
  ): TypedContractMethod<[gameId: string], [DETHRoll.GameStructOutput], "view">;
  getFunction(
    nameOrSignature: "getMinePendingGame"
  ): TypedContractMethod<
    [player: AddressLike],
    [DETHRoll.GameStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingGameForWallet"
  ): TypedContractMethod<
    [player: AddressLike],
    [DETHRoll.GameStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayer"
  ): TypedContractMethod<
    [player: AddressLike],
    [DETHRoll.PlayerStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRandomNumber"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserBalance"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "initGame"
  ): TypedContractMethod<
    [_betAmount: BigNumberish, player1: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "joinGame"
  ): TypedContractMethod<
    [gameId: string, oponent: AddressLike, player2: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<
    [_mainWallet: AddressLike, _discord: string, _sigWallet: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resetPlayer"
  ): TypedContractMethod<[player: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "roll"
  ): TypedContractMethod<
    [gameId: string, player: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sponsorWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "terminatePendingGame"
  ): TypedContractMethod<[player: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "GameCreated"
  ): TypedContractEvent<
    GameCreatedEvent.InputTuple,
    GameCreatedEvent.OutputTuple,
    GameCreatedEvent.OutputObject
  >;
  getEvent(
    key: "GameJoin"
  ): TypedContractEvent<
    GameJoinEvent.InputTuple,
    GameJoinEvent.OutputTuple,
    GameJoinEvent.OutputObject
  >;
  getEvent(
    key: "GameWon"
  ): TypedContractEvent<
    GameWonEvent.InputTuple,
    GameWonEvent.OutputTuple,
    GameWonEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Roll"
  ): TypedContractEvent<
    RollEvent.InputTuple,
    RollEvent.OutputTuple,
    RollEvent.OutputObject
  >;

  filters: {
    "GameCreated(uint256,address)": TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;
    GameCreated: TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;

    "GameJoin(string,uint256,address,address)": TypedContractEvent<
      GameJoinEvent.InputTuple,
      GameJoinEvent.OutputTuple,
      GameJoinEvent.OutputObject
    >;
    GameJoin: TypedContractEvent<
      GameJoinEvent.InputTuple,
      GameJoinEvent.OutputTuple,
      GameJoinEvent.OutputObject
    >;

    "GameWon(string,address,address,uint256)": TypedContractEvent<
      GameWonEvent.InputTuple,
      GameWonEvent.OutputTuple,
      GameWonEvent.OutputObject
    >;
    GameWon: TypedContractEvent<
      GameWonEvent.InputTuple,
      GameWonEvent.OutputTuple,
      GameWonEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Roll(string,address,uint256)": TypedContractEvent<
      RollEvent.InputTuple,
      RollEvent.OutputTuple,
      RollEvent.OutputObject
    >;
    Roll: TypedContractEvent<
      RollEvent.InputTuple,
      RollEvent.OutputTuple,
      RollEvent.OutputObject
    >;
  };
}
