/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWithdrawalUtilsV0,
  IWithdrawalUtilsV0Interface,
} from "../../../../../../@api3/airnode-protocol/contracts/rrp/interfaces/IWithdrawalUtilsV0";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "airnode",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sponsor",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "withdrawalRequestId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "address",
        name: "sponsorWallet",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "FulfilledWithdrawal",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "airnode",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sponsor",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "withdrawalRequestId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "address",
        name: "sponsorWallet",
        type: "address",
      },
    ],
    name: "RequestedWithdrawal",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "withdrawalRequestId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "airnode",
        type: "address",
      },
      {
        internalType: "address",
        name: "sponsor",
        type: "address",
      },
    ],
    name: "fulfillWithdrawal",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "airnode",
        type: "address",
      },
      {
        internalType: "address",
        name: "sponsorWallet",
        type: "address",
      },
    ],
    name: "requestWithdrawal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "sponsor",
        type: "address",
      },
    ],
    name: "sponsorToWithdrawalRequestCount",
    outputs: [
      {
        internalType: "uint256",
        name: "withdrawalRequestCount",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IWithdrawalUtilsV0__factory {
  static readonly abi = _abi;
  static createInterface(): IWithdrawalUtilsV0Interface {
    return new Interface(_abi) as IWithdrawalUtilsV0Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IWithdrawalUtilsV0 {
    return new Contract(address, _abi, runner) as unknown as IWithdrawalUtilsV0;
  }
}
